connection:
  client: FH-Bielefeld
  serverURI: https://ilias.hs-karlsruhe.de/login.php?target=&client_id=HSKA&auth_stat=
  user: 
  userId: 
  wsdl: https://ilias.hs-karlsruhe.de/webservice/soap/server.php?wsdl
courses:

localDir:
  path: 
  structureTemplate: '%. Semester ($)'
  useOwnNames: true
  useOwnStructure: true
  useYear: true
sync:
  ignoredFiles: 
  overwrite: false
  owIgnore: false
  showNew: false
  showOnly: false
  syncAll: true
  syncNotification: false
system:
  lang: en
  theme: dark
  trayicon: false
  updateCheck: false
